In [1]:
import pandas as pd
import numpy as np

## The need for data structures

### Data structures

In [2]:
sample_df_construction = pd.DataFrame({'col1': range(0, 100), 
                                       'col2': range(1, 200, 2)})

In [3]:
sample_df_construction.head()

   col1  col2
0     0     1
1     1     3
2     2     5
3     3     7
4     4     9

In [4]:
type(sample_df_construction)

pandas.core.frame.DataFrame

In [5]:
?pd.DataFrame

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

    .. versionchanged:: 1.3.0

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {'col1': [1, 2], 'col2': [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
...                    columns=['a', 'b', 'c'])
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
>>> df3 = pd.DataFrame(data, columns=['c', 'a'])
...
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           d:\python3.11.1\lib\site-packages\pandas\core\frame.py
Type:           type
Subclasses:     SubclassedDataFrame

In [6]:
sample_np_array_1 = np.array(range(0, 100))
sample_np_array_2 = np.array(range(1, 200, 2))
sample_np_2d = np.column_stack((sample_np_array_1, sample_np_array_2))
sample_df_from_np = pd.DataFrame(sample_np_2d, columns=['col1', 'col2'])
sample_df_from_np

    col1  col2
0      0     1
1      1     3
2      2     5
3      3     7
4      4     9
..   ...   ...
95    95   191
96    96   193
97    97   195
98    98   197
99    99   199

[100 rows x 2 columns]

In [7]:
list_1 = [i for i in range(100)]
list_2 = [i for i in range(1, 200, 2)]
sample_df_from_iterable = pd.DataFrame(zip(list_1, list_2), columns=['col1', 'col2'])
sample_df_from_iterable.head()

   col1  col2
0     0     1
1     1     3
2     2     5
3     3     7
4     4     9

In [8]:
sample_df_from_lists = pd.DataFrame({'col1': list_1, 'col2': list_2})

sample_df_from_lists.head()

   col1  col2
0     0     1
1     1     3
2     2     5
3     3     7
4     4     9

In [9]:
empty_data = pd.DataFrame()
empty_data.shape

(0, 0)

In [10]:
my_array = np.array([[0, 1, 2, 3, 4],
                     [2, 3, 4, 5, 6]])

filled_dataframe = pd.concat([empty_data, pd.DataFrame(my_array)], axis='index')
filled_dataframe

   0  1  2  3  4
0  0  1  2  3  4
1  2  3  4  5  6

## Indexes and columns