In [1]:
print("""
@File         : 102.basic numerical operations.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-06-18 22:13:38
@Email        : cuixuanstephen@gmail.com
@Description  : basic numerical operations with pandas
""")

@File         : 102.basic numerical operations.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-06-18 22:13:38
@Email        : cuixuanstephen@gmail.com
@Description  : basic numerical operations with pandas

In [2]:
import pandas as pd
import numpy as np
import random

In [3]:
np.random.seed(123)

In [4]:
ser1 = pd.Series(np.random.normal(3.0, 1, 100))
ser2 = pd.Series(np.random.normal(5.0, 3, 100))
ser3 = pd.Series(np.random.normal(1.0, 0.5, 100))

In [25]:
df = pd.concat([ser1, ser2, ser3], axis='columns')
df.columns = ['V1','V2','V3']
df.head()

         V1         V2        V3
0  1.914369   6.926164  1.351655
1  3.997345  -0.933664  0.700947
2  3.282978   7.136794  2.100351
3  1.493705  12.794912  1.344148
4  2.421400   4.926122  0.996846

In [26]:
df.sum()

V1    302.710907
V2    494.139331
V3     95.243434
dtype: float64

In [27]:
df.mean()

V1    3.027109
V2    4.941393
V3    0.952434
dtype: float64

In [28]:
df.apply(lambda ser: divmod(ser, 3))

,V1,V2,V3
0,0 0.0 1 1.0 2 1.0 3 0.0 4 ...,0 2.0 1 -1.0 2 2.0 3 4.0 4 ...,0 0.0 1 0.0 2 0.0 3 0.0 4 ...
1,0 1.914369 1 0.997345 2 0.282978 3...,0 0.926164 1 2.066336 2 1.136794 3...,0 1.351655 1 0.700947 2 2.100351 3...

> `apply` 返回的类型会让人感觉非常奇怪。

In [29]:
df.map(lambda element: divmod(element, 3))

,V1,V2,V3
0,"(0.0, 1.9143693966994388)","(2.0, 0.9261640678154937)","(0.0, 1.3516550589033651)"
1,"(1.0, 0.9973454465835858)","(-1.0, 2.0663362054386534)","(0.0, 0.7009473343295873)"
2,"(1.0, 0.28297849805199204)","(2.0, 1.1367939064115546)","(0.0, 2.1003510496085642)"
3,"(0.0, 1.493705286081908)","(4.0, 0.7949117818079436)","(0.0, 1.3441484651110442)"
4,"(0.0, 2.4213997480314635)","(1.0, 1.9261220557055578)","(0.0, 0.9968463745430639)"
...,...,...,...
95,"(1.0, 1.031114458921742)","(-2.0, 1.3068349762420635)","(0.0, 1.347893659569804)"
96,"(0.0, 1.9154320879942335)","(1.0, 1.1921195307477372)","(0.0, 1.9379002733568176)"
97,"(0.0, 1.6365284553814157)","(1.0, 1.6674478368409789)","(0.0, 1.207847269946217)"
98,"(1.0, 0.37940061207813613)","(1.0, 0.9762148513802424)","(0.0, 1.080272210739859)"
99,"(0.0, 2.6208235654274477)","(1.0, 1.3461612136911745)","(0.0, 1.4098803048050945)"

In [30]:
list1 = [['20']*10, ['35']*15, ['40']*10, ['10']*25, ['15']*40]

char_list = [x for sublist in list1 for x in sublist]
len(char_list)

100

In [31]:
random.seed(123)

In [32]:
random.shuffle(char_list)

In [33]:
ser4 = pd.Series(char_list)
ser4

0     15
1     40
2     15
3     10
4     15
      ..
95    15
96    10
97    35
98    40
99    20
Length: 100, dtype: object

In [34]:
ser4 = pd.to_numeric(ser4)
ser4

0     15
1     40
2     15
3     10
4     15
      ..
95    15
96    10
97    35
98    40
99    20
Length: 100, dtype: int64

In [36]:
df = pd.concat([df, ser4], axis='columns')
df.rename(columns={0: 'V4'}, inplace=True)
df.sample(2)

          V1        V2        V3  V4  V4
74  0.876900  6.209258  0.339699  20  20
79  1.394037  5.419934  0.666596  20  20

In [37]:
numpy_array = df.to_numpy()
numpy_array

array([[ 1.91436940e+00,  6.92616407e+00,  1.35165506e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 3.99734545e+00, -9.33663795e-01,  7.00947334e-01,
         4.00000000e+01,  4.00000000e+01],
       [ 3.28297850e+00,  7.13679391e+00,  2.10035105e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 1.49370529e+00,  1.27949118e+01,  1.34414847e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 2.42139975e+00,  4.92612206e+00,  9.96846375e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 4.65143654e+00,  5.10242639e+00,  8.96668848e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 5.73320757e-01,  5.53864845e+00,  9.56738857e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 2.57108737e+00, -5.85927132e-01,  5.42346465e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 4.26593626e+00,  6.27843992e+00,  9.52398730e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.13325960e+00,  1.83770768e-01,  1.13934176e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 2.32111385e+00,  3.71696121e+00,  1.28977081e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 2.90529103e+00,  8.72860865e+00,  1.28984489e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 4.49138963e+00,  2.79434913e+00,  8.62561227e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 2.36109800e+00,  6.50374697e+00,  2.91958874e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 2.55601804e+00,  8.03821716e+00,  6.65448687e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 2.56564872e+00,  5.83622257e+00,  1.80609652e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 5.20593008e+00,  8.87154590e-01,  1.44802916e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 5.18678609e+00,  4.00257417e+00,  1.18480979e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 4.00405390e+00,  1.08782340e+01,  6.19352878e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 3.38618640e+00, -1.07513729e+00,  1.00182258e+00,
         4.00000000e+01,  4.00000000e+01],
       [ 3.73736858e+00,  4.17264196e+00,  3.72165657e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 4.49073203e+00,  3.34367579e+00,  7.24031562e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.06416613e+00,  5.36224209e+00,  8.77398329e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 4.17582904e+00,  7.24464685e+00,  8.19180034e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 1.74611933e+00,  9.82607290e+00,  1.47830097e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 2.36224850e+00,  4.18930282e+00,  2.90637043e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 3.90710520e+00,  7.43702399e+00,  5.67283864e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 1.57131930e+00,  6.49922043e+00,  3.12656014e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 2.85993128e+00,  6.42304189e+00,  3.81323394e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 2.13824510e+00,  3.30822821e+00,  1.06202795e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 2.74438063e+00,  2.00803559e+00,  1.99779733e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 2.01410895e-01,  1.69987066e+00,  1.37693439e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 1.22846690e+00,  2.73068837e+00,  8.76592112e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.30012277e+00,  5.96505973e+00,  1.03439417e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 3.92746243e+00,  7.28284818e+00,  1.16128837e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 2.82636432e+00,  5.97040654e+00,  7.82916740e-01,
         4.00000000e+01,  4.00000000e+01],
       [ 3.00284592e+00,  3.35313471e+00,  1.51623986e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 3.68822271e+00,  1.04179103e+01,  9.02828637e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.12046366e+00,  9.55659687e+00,  1.29703513e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 3.28362732e+00,  3.93799966e+00,  9.00443809e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.19463348e+00,  2.52970578e+00,  1.14543719e+00,
         4.00000000e+01,  4.00000000e+01],
       [ 1.27233051e+00,  5.39064486e+00,  1.13983134e+00,
         4.00000000e+01,  4.00000000e+01],
       [ 2.60910021e+00,  8.80189594e+00,  1.12498497e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 3.57380586e+00,  5.99829493e+00,  5.12846075e-01,
         4.00000000e+01,  4.00000000e+01],
       [ 3.33858905e+00,  6.66964611e+00,  1.21793789e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 2.98816951e+00,  4.36375963e+00,  8.40521505e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 5.39236527e+00,  6.36881269e+00,  1.31524402e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 3.41291216e+00,  9.63363335e+00, -7.62467222e-02,
         1.00000000e+01,  1.00000000e+01],
       [ 3.97873601e+00,  4.28099366e+00,  2.67441889e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 5.23814334e+00,  5.42992320e+00,  1.18172278e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 1.70591468e+00,  5.76144943e+00,  1.93146379e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 1.96121179e+00,  5.85117607e+00,  1.41752937e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 4.74371223e+00,  7.64333372e-01,  6.58774533e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 2.20193726e+00, -6.30605968e-01,  1.53973792e-01,
         4.00000000e+01,  4.00000000e+01],
       [ 3.02968323e+00,  1.94103479e+00,  1.37134311e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 4.06931597e+00,  5.50382689e+00,  9.59708389e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 3.89070639e+00,  6.66156850e+00,  1.29535211e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 4.75488618e+00,  3.40797632e+00,  1.05764936e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 4.49564414e+00,  9.13177245e+00,  1.01482146e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 4.06939267e+00,  4.57047208e+00,  2.47931272e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 2.22729129e+00,  5.06094799e+00,  9.96935019e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 3.79486267e+00,  4.41810839e+00,  9.20377395e-01,
         4.00000000e+01,  4.00000000e+01],
       [ 3.31427199e+00,  5.40208038e+00,  9.39275662e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 1.67373454e+00,  7.11342222e+00,  7.08231642e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 4.41729905e+00,  6.99696031e+00,  1.49506645e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 3.80723653e+00,  2.30473118e+00,  8.23122833e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 3.04549008e+00,  9.57099133e+00,  1.31797135e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 2.76690794e+00,  1.71492063e+00,  1.14230151e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 1.80169886e+00,  5.23768104e+00,  1.60949293e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 3.19952407e+00,  4.17681028e+00,  1.21008980e+00,
         2.00000000e+01,  2.00000000e+01],
       [ 3.46843912e+00,  1.85302497e+00,  3.93307610e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.16884502e+00,  4.77463824e+00,  3.36756107e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 4.16220405e+00,  2.77755868e+00,  1.70418457e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 1.90279695e+00,  5.21872173e+00,  6.95644598e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 8.76899650e-01,  6.20925788e+00,  3.39698710e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 4.03972709e+00,  9.41578811e+00,  6.65190700e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.59663396e+00,  5.92215266e+00,  1.63231264e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 2.87397041e+00,  3.16632398e+00,  2.89893501e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.16248328e+00,  3.82514057e+00,  5.66752398e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 1.39403724e+00,  5.41993432e+00,  6.66596246e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 4.25523737e+00,  5.28038249e+00,  3.74405063e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.31113102e+00,  9.37876780e+00,  4.07836331e-01,
         4.00000000e+01,  4.00000000e+01],
       [ 4.66095249e+00,  9.18605879e+00,  2.40946012e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 3.80730819e+00,  3.92319222e+00,  7.69406293e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 2.68524185e+00,  3.35407362e+00,  8.22545584e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 1.91409760e+00, -2.67116381e+00,  6.58730923e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 2.26753801e+00,  3.35323876e+00,  1.73151081e-01,
         3.50000000e+01,  3.50000000e+01],
       [ 1.78747687e+00,  2.06582688e+00,  1.62666797e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 5.08711336e+00,  3.93552663e+00,  3.35460585e-01,
         1.00000000e+01,  1.00000000e+01],
       [ 3.16444123e+00,  6.17475273e+00,  1.13901686e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 4.15020554e+00,  5.53157699e+00,  4.62616703e-01,
         1.50000000e+01,  1.50000000e+01],
       [ 1.73264795e+00,  4.91009598e+00,  1.33415843e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 3.18103513e+00,  5.59874633e+00,  1.47791618e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 4.17786194e+00,  4.62164668e+00,  5.61193207e-01,
         2.00000000e+01,  2.00000000e+01],
       [ 2.66498924e+00,  5.59105680e+00,  3.81421352e-02,
         3.50000000e+01,  3.50000000e+01],
       [ 4.03111446e+00, -4.69316502e+00,  1.34789366e+00,
         1.50000000e+01,  1.50000000e+01],
       [ 1.91543209e+00,  4.19211953e+00,  1.93790027e+00,
         1.00000000e+01,  1.00000000e+01],
       [ 1.63652846e+00,  4.66744784e+00,  1.20784727e+00,
         3.50000000e+01,  3.50000000e+01],
       [ 3.37940061e+00,  3.97621485e+00,  1.08027221e+00,
         4.00000000e+01,  4.00000000e+01],
       [ 2.62082357e+00,  4.34616121e+00,  1.40988030e+00,
         2.00000000e+01,  2.00000000e+01]])