In [2]:
print("""
@File         : pd.dataframe.T.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-01-04 14:37:18
@Email        : cuixuanstephen@gmail.com
@Description  : Transposing with pd.DataFrame.T
""")

@File         : pd.dataframe.T.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-01-04 14:37:18
@Email        : cuixuanstephen@gmail.com
@Description  : Transposing with pd.DataFrame.T

转置是指反转 pd.DataFrame 的过程，使行变为列，列变为行：

In [3]:
import pandas as pd

![Transposing a pd.DataFrame](../../IMAGES/FIG7-8.png)

In [4]:
df = pd.DataFrame([
    [1, 2, 3],
    [4, 5, 6],
], columns=list("xyz"), index=list("ab"))

df

   x  y  z
a  1  2  3
b  4  5  6

In [5]:
df.T

   a  b
x  1  4
y  2  5
z  3  6

转置的主要用例之一是在 apply function 之前将 pd.DataFrame 设置为最佳格式。

In [6]:
df.sum(axis='columns')

a     6
b    15
dtype: int64

使用 `axis=1` 参数会大大降低应用程序的性能。如果发现在整个代码中分散了大量 `axis=1` 调用，那么最好先转置数据，然后应用默认 `axis=0` 的函数。

In [7]:
import numpy as np

In [8]:
np.random.seed(42)

df = pd.DataFrame(
    np.random.randint(10, size=(2, 10_000)),
    index=list('ab')
)

df

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
a,6,3,7,4,6,9,2,6,7,4,...,7,3,6,3,4,6,9,2,9,4
b,2,4,2,9,6,0,8,8,4,8,...,4,2,9,5,1,5,5,1,5,5

In [9]:
df.sum(axis='columns')

a    44972
b    45097
dtype: int64

In [10]:
df.T.sum()

a    44972
b    45097
dtype: int64

如果使用 `axis=1` 作为参数反复进行调用，会发现先转置可以节省大量时间。

In [11]:
import timeit

def baseline_sum():
    for _ in range(100):
        df.sum(axis='columns')
    
    
timeit.timeit(baseline_sum, number=100)

7.866787300001306

In [12]:
def transposed_sum():
    transposed = df.T
    for _ in range(100):
        transposed.sum()
        
    
timeit.timeit(transposed_sum, number=100)

1.376591100000951

总的来说，使用 `pd.DataFrame.T` 来避免后续使用 `axis=1` 的调用是一种非常值得提倡的做法。