In [1]:
import pandas as pd

In [2]:
store1 = pd.read_csv('Store1.csv')
store2 = pd.read_csv('Store2.csv')

In [4]:
store1.sample(5)

   Months  Grocery_sales  Stationary_sales
25    Mar             72                97
49    Mar             29               113
47    Mar             47                41
13    Feb             31                13
37    Mar             43               137

In [5]:
store2.sample(5)

   Months  Grocery_sales  Stationary_sales
57    Mar             65                10
66    Mar             40                78
60    Mar             47                53
40    Mar              5                40
31    Feb             22                 8

In [11]:
sales_sum1 = store1[['Grocery_sales', 'Stationary_sales']].sum()

In [12]:
sales_sum2 = store2[['Grocery_sales', 'Stationary_sales']].sum()

In [15]:
store1[store1['Months'] == 'Mar'][['Grocery_sales', 'Stationary_sales']].sum()

Grocery_sales       1083
Stationary_sales    1788
dtype: int64

In [16]:
store2[store2['Months'] == 'Mar'][['Grocery_sales', 'Stationary_sales']].sum()

Grocery_sales       1009
Stationary_sales    1369
dtype: int64

In [29]:
len(store1[store1['Stationary_sales'].gt(store2['Stationary_sales'])])

C:\Users\JPL-JUNO\AppData\Local\Temp\ipykernel_1576\2360348277.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  len(store1[store1['Stationary_sales'].gt(store2['Stationary_sales'])])

35

> 注意：`store1` 的长度没有 `store2` 长，数量上不匹配。